// ─────────────────────────────────────────────────────────────────────────────
// CSS Animations Code Generator
// Generates @keyframes and animation CSS from AnimationSpec entries.
// ─────────────────────────────────────────────────────────────────────────────

import type { AnimationSpec } from "./framer-motion.js";

const EASING_CSS_MAP: Record<string, string> = {
  EASE_IN:     "cubic-bezier(0.4, 0, 1, 1)",
  EASE_OUT:    "cubic-bezier(0, 0, 0.2, 1)",
  EASE_IN_OUT: "cubic-bezier(0.4, 0, 0.2, 1)",
  LINEAR:      "cubic-bezier(0, 0, 1, 1)",
  SPRING:      "cubic-bezier(0.4, 0, 0.2, 1)",
};

function getSlideAxis(type: string, dir: string): { axis: "x" | "y"; sign: number } {
  const isOut = type === "SLIDE_OUT" || type === "MOVE_OUT";
  if (dir === "LEFT")  return { axis: "x", sign: isOut ? -1 :  1 };
  if (dir === "RIGHT") return { axis: "x", sign: isOut ?  1 : -1 };
  if (dir === "UP")    return { axis: "y", sign: isOut ? -1 :  1 };
  return { axis: "y", sign: isOut ? 1 : -1 };
}

export function generateCSS(specs: AnimationSpec[]): string {
  const lines: string[] = [
    "/* Generated by figma-intelligence-layer animation-specifier */",
    "",
  ];

  for (const spec of specs) {
    const type = spec.type.toUpperCase();
    const dir = spec.direction.toUpperCase();
    const name = spec.name;
    const durationMs = Math.round(spec.duration * 1000);
    const easingCss = EASING_CSS_MAP[spec.easing] ?? "ease-in-out";

    if (type === "DISSOLVE") {
      lines.push(`@keyframes ${name}FadeIn {`);
      lines.push(`  from { opacity: 0; }`);
      lines.push(`  to   { opacity: 1; }`);
      lines.push(`}`);
      lines.push(`.${name} { animation: ${name}FadeIn ${durationMs}ms ${easingCss} forwards; }`);
    } else if (type === "SMART_ANIMATE") {
      lines.push(`@keyframes ${name}Morph {`);
      lines.push(`  from { opacity: 0; transform: scale(0.95); }`);
      lines.push(`  to   { opacity: 1; transform: scale(1); }`);
      lines.push(`}`);
      lines.push(`.${name} { animation: ${name}Morph ${durationMs}ms ${easingCss} forwards; }`);
    } else if (["PUSH", "SLIDE_IN", "SLIDE_OUT", "MOVE_IN", "MOVE_OUT"].includes(type)) {
      const { axis, sign } = getSlideAxis(type, dir);
      const translateFn = axis === "x" ? "translateX" : "translateY";
      lines.push(`@keyframes ${name}SlideIn {`);
      lines.push(`  from { opacity: 0; transform: ${translateFn}(${sign * 100}%); }`);
      lines.push(`  to   { opacity: 1; transform: ${translateFn}(0); }`);
      lines.push(`}`);
      lines.push(`.${name} { animation: ${name}SlideIn ${durationMs}ms ${easingCss} forwards; }`);
    } else {
      lines.push(`@keyframes ${name} {`);
      lines.push(`  from { opacity: 0; }`);
      lines.push(`  to   { opacity: 1; }`);
      lines.push(`}`);
      lines.push(`.${name} { animation: ${name} ${durationMs}ms ${easingCss} forwards; }`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
