// ─────────────────────────────────────────────────────────────────────────────
// Framer Motion Code Generator
// Generates Framer Motion `Variants` objects from AnimationSpec entries.
// ─────────────────────────────────────────────────────────────────────────────

export interface AnimationSpec {
  name: string;
  fromId: string;
  toId: string;
  duration: number;
  easing: string;
  easingValues: number[];
  direction: string;
  type: string;
  isSpring: boolean;
  springStiffness?: number;
  springDamping?: number;
}

function getClosedVariant(spec: AnimationSpec): Record<string, unknown> {
  const closed: Record<string, unknown> = { opacity: 0 };
  const type = spec.type.toUpperCase();

  if (type === "SMART_ANIMATE") {
    closed["scale"] = 0.96;
  } else if (type === "PUSH" || type === "SLIDE_IN" || type === "MOVE_IN") {
    const dir = spec.direction.toUpperCase();
    if (dir === "LEFT") closed["x"] = -100;
    else if (dir === "RIGHT") closed["x"] = 100;
    else if (dir === "UP") closed["y"] = -100;
    else closed["y"] = 100;
  }

  return closed;
}

export function generateFramerMotion(specs: AnimationSpec[]): string {
  const lines: string[] = [
    "// Generated by figma-intelligence-layer animation-specifier",
    'import { Variants } from "framer-motion";',
    "",
  ];

  for (const spec of specs) {
    const varName = `${spec.name}Variants`;
    const closedVariant = getClosedVariant(spec);
    const openVariant: Record<string, unknown> = { opacity: 1 };

    for (const key of Object.keys(closedVariant)) {
      if (key !== "opacity" && key !== "scale") openVariant[key] = 0;
      if (key === "scale") openVariant[key] = 1;
    }

    let transition: Record<string, unknown>;
    if (spec.isSpring) {
      transition = {
        type: "spring",
        stiffness: spec.springStiffness ?? 300,
        damping: spec.springDamping ?? 30,
      };
    } else {
      transition = { duration: spec.duration, ease: spec.easingValues };
    }

    lines.push(`export const ${varName}: Variants = {`);
    lines.push(`  closed: ${JSON.stringify(closedVariant)},`);
    lines.push(`  open: {`);
    lines.push(`    ...${JSON.stringify(openVariant)},`);
    lines.push(`    transition: ${JSON.stringify(transition)},`);
    lines.push(`  },`);
    lines.push(`};`);
    lines.push("");
    lines.push(`// Usage: <motion.div variants={${varName}} initial="closed" animate="open" />`);
    lines.push("");
  }

  return lines.join("\n");
}
