// ─────────────────────────────────────────────────────────────────────────────
// Swift Animations Code Generator
// Generates SwiftUI and UIKit animation code from AnimationSpec entries.
// ─────────────────────────────────────────────────────────────────────────────

import type { AnimationSpec } from "./framer-motion.js";

const EASING_SWIFT_MAP: Record<string, string> = {
  EASE_IN:     ".easeIn",
  EASE_OUT:    ".easeOut",
  EASE_IN_OUT: ".easeInOut",
  LINEAR:      ".linear",
  SPRING:      ".spring(response: 0.4, dampingFraction: 0.7)",
};

export function generateSwift(specs: AnimationSpec[]): string {
  const lines: string[] = [
    "// Generated by figma-intelligence-layer animation-specifier",
    "import SwiftUI",
    "import UIKit",
    "",
    "// MARK: - SwiftUI Animations",
    "",
  ];

  for (const spec of specs) {
    const type = spec.type.toUpperCase();
    const dir = spec.direction.toUpperCase();
    const swiftEasing = EASING_SWIFT_MAP[spec.easing] ?? ".easeInOut";
    const durationStr = spec.duration.toFixed(3);
    const name = spec.name;

    lines.push(`// Transition: ${spec.fromId} → ${spec.toId}`);

    if (spec.isSpring) {
      lines.push(`func ${name}Animation(isVisible: Binding<Bool>) -> some View {`);
      lines.push(`  content`);
      lines.push(`    .opacity(isVisible.wrappedValue ? 1 : 0)`);
      lines.push(`    .animation(.spring(response: ${durationStr}, dampingFraction: 0.7), value: isVisible.wrappedValue)`);
      lines.push(`}`);
    } else if (type === "DISSOLVE") {
      lines.push(`func ${name}Animation(isVisible: Binding<Bool>) -> some View {`);
      lines.push(`  content`);
      lines.push(`    .opacity(isVisible.wrappedValue ? 1 : 0)`);
      lines.push(`    .animation(.easeInOut(duration: ${durationStr}), value: isVisible.wrappedValue)`);
      lines.push(`}`);
    } else if (type === "SMART_ANIMATE") {
      lines.push(`func ${name}Animation(isVisible: Binding<Bool>) -> some View {`);
      lines.push(`  content`);
      lines.push(`    .opacity(isVisible.wrappedValue ? 1 : 0)`);
      lines.push(`    .scaleEffect(isVisible.wrappedValue ? 1 : 0.95)`);
      lines.push(`    .animation(${swiftEasing}(duration: ${durationStr}), value: isVisible.wrappedValue)`);
      lines.push(`}`);
    } else if (["PUSH", "SLIDE_IN", "SLIDE_OUT", "MOVE_IN", "MOVE_OUT"].includes(type)) {
      const isHorizontal = dir === "LEFT" || dir === "RIGHT";
      const offsetEdge = dir === "LEFT" ? "-UIScreen.main.bounds.width"
        : dir === "RIGHT" ? "UIScreen.main.bounds.width"
        : dir === "UP" ? "-UIScreen.main.bounds.height"
        : "UIScreen.main.bounds.height";

      lines.push(`func ${name}Animation(isVisible: Binding<Bool>) -> some View {`);
      lines.push(`  content`);
      lines.push(`    .offset(${isHorizontal ? "x" : "y"}: isVisible.wrappedValue ? 0 : ${offsetEdge})`);
      lines.push(`    .opacity(isVisible.wrappedValue ? 1 : 0)`);
      lines.push(`    .animation(${swiftEasing}(duration: ${durationStr}), value: isVisible.wrappedValue)`);
      lines.push(`}`);
    } else {
      lines.push(`func ${name}Animation(isVisible: Binding<Bool>) -> some View {`);
      lines.push(`  content`);
      lines.push(`    .opacity(isVisible.wrappedValue ? 1 : 0)`);
      lines.push(`    .animation(${swiftEasing}(duration: ${durationStr}), value: isVisible.wrappedValue)`);
      lines.push(`}`);
    }

    lines.push("");

    // UIKit equivalent
    lines.push(`// UIKit equivalent for ${name}`);
    lines.push(`func ${name}UIKitAnimate(view: UIView, isShowing: Bool) {`);
    if (spec.isSpring) {
      lines.push(`  let animator = UIViewPropertyAnimator(duration: ${durationStr}, dampingRatio: 0.7) {`);
    } else {
      lines.push(`  let animator = UIViewPropertyAnimator(duration: ${durationStr}, curve: ${swiftEasing}) {`);
    }
    lines.push(`    view.alpha = isShowing ? 1 : 0`);
    lines.push(`  }`);
    lines.push(`  animator.startAnimation()`);
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}
