/**
 * Component type detection — identifies component type and returns guidance hints
 * Guidance hints tell extractors what to look for, NOT content to output verbatim.
 */
import type { NodeSnapshot, ComponentTypeGuidance } from "./types.js";

const GUIDANCE_MAP: Record<string, ComponentTypeGuidance> = {
  button: {
    expectedElements: ["label", "icon", "container"],
    expectedVariantAxes: ["size", "hierarchy", "state", "type"],
    expectedStates: ["default", "hover", "pressed", "disabled", "focused", "loading"],
    semanticRole: "button",
    wcagPattern: "button",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text, 3:1 non-text",
  },
  input: {
    expectedElements: ["label", "field", "placeholder", "helper text", "icon"],
    expectedVariantAxes: ["size", "state", "type"],
    expectedStates: ["default", "focused", "filled", "error", "disabled", "read-only"],
    semanticRole: "textbox",
    wcagPattern: "text-field",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text, 3:1 border",
  },
  select: {
    expectedElements: ["label", "trigger", "chevron", "option", "placeholder"],
    expectedVariantAxes: ["size", "state"],
    expectedStates: ["default", "open", "focused", "disabled", "error"],
    semanticRole: "combobox",
    wcagPattern: "listbox",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text, 3:1 border",
  },
  checkbox: {
    expectedElements: ["box", "checkmark", "label"],
    expectedVariantAxes: ["size", "state"],
    expectedStates: ["unchecked", "checked", "indeterminate", "disabled"],
    semanticRole: "checkbox",
    wcagPattern: "checkbox",
    minTouchTarget: 44,
    contrastRequirement: "3:1 non-text (box border)",
  },
  radio: {
    expectedElements: ["circle", "dot", "label"],
    expectedVariantAxes: ["size", "state"],
    expectedStates: ["unselected", "selected", "disabled"],
    semanticRole: "radio",
    wcagPattern: "radio-group",
    minTouchTarget: 44,
    contrastRequirement: "3:1 non-text (circle border)",
  },
  toggle: {
    expectedElements: ["track", "thumb", "label"],
    expectedVariantAxes: ["size", "state"],
    expectedStates: ["off", "on", "disabled"],
    semanticRole: "switch",
    wcagPattern: "switch",
    minTouchTarget: 44,
    contrastRequirement: "3:1 non-text",
  },
  tabs: {
    expectedElements: ["tab", "indicator", "content"],
    expectedVariantAxes: ["size", "state", "orientation"],
    expectedStates: ["default", "active", "hover", "disabled"],
    semanticRole: "tablist",
    wcagPattern: "tabs",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text",
  },
  modal: {
    expectedElements: ["header", "body", "footer", "close", "overlay"],
    expectedVariantAxes: ["size", "type"],
    expectedStates: ["default"],
    semanticRole: "dialog",
    wcagPattern: "dialog-modal",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text",
  },
  toast: {
    expectedElements: ["message", "icon", "close", "action"],
    expectedVariantAxes: ["type", "state"],
    expectedStates: ["info", "success", "warning", "error"],
    semanticRole: "alert",
    wcagPattern: "alert",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text",
  },
  card: {
    expectedElements: ["image", "title", "body", "footer", "action"],
    expectedVariantAxes: ["variant", "size"],
    expectedStates: ["default", "hover", "selected"],
    semanticRole: "article",
    wcagPattern: "card",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text, 3:1 border",
  },
  chip: {
    expectedElements: ["label", "icon", "close"],
    expectedVariantAxes: ["size", "variant", "state"],
    expectedStates: ["default", "selected", "disabled"],
    semanticRole: "button",
    wcagPattern: "button",
    minTouchTarget: 32,
    contrastRequirement: "4.5:1 text, 3:1 non-text",
  },
  avatar: {
    expectedElements: ["image", "initials", "icon", "badge"],
    expectedVariantAxes: ["size", "variant"],
    expectedStates: ["default"],
    semanticRole: "img",
    wcagPattern: "img",
    minTouchTarget: 44,
    contrastRequirement: "3:1 non-text",
  },
  tooltip: {
    expectedElements: ["content", "arrow"],
    expectedVariantAxes: ["placement"],
    expectedStates: ["default"],
    semanticRole: "tooltip",
    wcagPattern: "tooltip",
    minTouchTarget: 0,
    contrastRequirement: "4.5:1 text",
  },
  accordion: {
    expectedElements: ["header", "content", "chevron", "title"],
    expectedVariantAxes: ["state"],
    expectedStates: ["collapsed", "expanded", "disabled"],
    semanticRole: "region",
    wcagPattern: "accordion",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text",
  },
  badge: {
    expectedElements: ["label", "dot"],
    expectedVariantAxes: ["variant", "size"],
    expectedStates: ["default"],
    semanticRole: "status",
    wcagPattern: "status",
    minTouchTarget: 0,
    contrastRequirement: "4.5:1 text, 3:1 non-text",
  },
  alert: {
    expectedElements: ["icon", "title", "message", "close", "action"],
    expectedVariantAxes: ["variant", "type"],
    expectedStates: ["info", "success", "warning", "error"],
    semanticRole: "alert",
    wcagPattern: "alert",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text",
  },
  slider: {
    expectedElements: ["track", "thumb", "label", "value"],
    expectedVariantAxes: ["size", "state"],
    expectedStates: ["default", "hover", "active", "disabled"],
    semanticRole: "slider",
    wcagPattern: "slider",
    minTouchTarget: 44,
    contrastRequirement: "3:1 non-text",
  },
  table: {
    expectedElements: ["header", "row", "cell", "sort"],
    expectedVariantAxes: ["variant"],
    expectedStates: ["default"],
    semanticRole: "table",
    wcagPattern: "table",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text",
  },
  navigation: {
    expectedElements: ["logo", "nav items", "actions", "menu"],
    expectedVariantAxes: ["variant"],
    expectedStates: ["default"],
    semanticRole: "navigation",
    wcagPattern: "navigation",
    minTouchTarget: 44,
    contrastRequirement: "4.5:1 text",
  },
  progress: {
    expectedElements: ["track", "fill", "label"],
    expectedVariantAxes: ["variant", "size"],
    expectedStates: ["default", "indeterminate", "complete"],
    semanticRole: "progressbar",
    wcagPattern: "meter",
    minTouchTarget: 0,
    contrastRequirement: "3:1 non-text",
  },
};

const TYPE_PATTERNS: [RegExp, string][] = [
  [/button|btn|cta/i, "button"],
  [/input|text.?field/i, "input"],
  [/select|dropdown/i, "select"],
  [/checkbox|check.?box/i, "checkbox"],
  [/radio/i, "radio"],
  [/toggle|switch/i, "toggle"],
  [/\btab\b/i, "tabs"],
  [/modal|dialog/i, "modal"],
  [/toast|snackbar/i, "toast"],
  [/card/i, "card"],
  [/chip|tag/i, "chip"],
  [/avatar/i, "avatar"],
  [/tooltip/i, "tooltip"],
  [/accordion/i, "accordion"],
  [/badge/i, "badge"],
  [/alert|banner/i, "alert"],
  [/slider|range/i, "slider"],
  [/table|data.?grid/i, "table"],
  [/nav|breadcrumb|menu/i, "navigation"],
  [/progress|loading|spinner/i, "progress"],
];

export function detectComponentType(snapshot: NodeSnapshot): { type?: string; guidance?: ComponentTypeGuidance } {
  const name = snapshot.name.toLowerCase();

  for (const [pattern, type] of TYPE_PATTERNS) {
    if (pattern.test(name)) {
      return { type, guidance: GUIDANCE_MAP[type] };
    }
  }

  return {};
}
